In [14]:
import os
os.getcwd()
import pandas as pd

df = pd.read_csv("C:\\Users\\syedh\\OneDrive\\Documents\\Data_Analysis\\archive\\ecommerce_transactions.csv")
df.head()

,Transaction_ID,User_Name,Age,Country,Product_Category,Purchase_Amount,Payment_Method,Transaction_Date
0,1,Ava Hall,63,Mexico,Clothing,780.69,Debit Card,2023-04-14
1,2,Sophia Hall,59,India,Beauty,738.56,PayPal,2023-07-30
2,3,Elijah Thompson,26,France,Books,178.34,Credit Card,2023-09-17
3,4,Elijah White,43,Mexico,Sports,401.09,UPI,2023-06-21
4,5,Ava Harris,48,Germany,Beauty,594.83,Net Banking,2024-10-29

In [16]:
df.tail()

df.info()

df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    50000 non-null  int64
 1   User_Name         50000 non-null  object
 2   Age               50000 non-null  int64
 3   Country           50000 non-null  object
 4   Product_Category  50000 non-null  object
 5   Purchase_Amount   50000 non-null  float64
 6   Payment_Method    50000 non-null  object
 7   Transaction_Date  50000 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 3.1+ MB

       Transaction_ID           Age  Purchase_Amount
count    50000.000000  50000.000000     50000.000000
mean     25000.500000     43.968680       503.159793
std      14433.901067     15.260578       286.563558
min          1.000000     18.000000         5.040000
25%      12500.750000     31.000000       255.450000
50%      25000.500000     44.000000       503.110000
75%      37500.250000     57.000000       751.162500
max      50000.000000     70.000000       999.980000

Calculated Average Order value (AOV)

In [ ]:

aov = df['Purchase_Amount'].mean()
print(f"Average Order Value (AOV): {aov:.2f}")

Average Order Value (AOV): 503.16

In [34]:
total_revenue = df['Purchase_Amount'].sum()
total_orders = len(df)
aov = total_revenue / total_orders
print(f"Total Revenue: ${total_revenue:,.2f}")
print(f"Average Order Value: ${aov:.2f}")
# See AOV by Category
df.groupby('Product_Category')['Purchase_Amount'].mean().sort_values(ascending=False)

Total Revenue: $25,157,989.65
Average Order Value: $503.16

Product_Category
Clothing          509.515739
Books             508.859316
Sports            506.231923
Beauty            503.273710
Grocery           502.587212
Home & Kitchen    500.716022
Toys              498.381158
Electronics       495.880544
Name: Purchase_Amount, dtype: float64

Repeat customer rate

In [ ]:
user_counts = df['User_Name'].value_counts()
print(user_counts)

repeat_customers = user_counts[user_counts > 1].count()
total_unique_customers = user_counts.count()

rcr = (repeat_customers / total_unique_customers) * 100

print(f"Repeat Customer Rate: {rcr:.2f}%")

Sophia Harris        568
Emma Clark           546
James Allen          545
Noah Anderson        545
James Lewis          543
                    ...
Noah White           460
Isabella Clark       458
Elijah White         456
Isabella Thompson    456
Oliver Rodriguez     435
Name: User_Name, Length: 100, dtype: int64
Repeat Customer Rate: 100.00%

Top products by popularity

In [37]:
category_popularity = df['Product_Category'].value_counts()
print(category_popularity)

Toys              6392
Electronics       6320
Sports            6312
Books             6253
Clothing          6224
Grocery           6215
Home & Kitchen    6209
Beauty            6075
Name: Product_Category, dtype: int64

Top products by category

In [38]:
category_revenue = df.groupby('Product_Category')['Purchase_Amount'].sum().sort_values(ascending=False)
print(category_revenue)

Product_Category
Sports            3195335.90
Toys              3185652.36
Books             3181897.30
Clothing          3171225.96
Electronics       3133965.04
Grocery           3123579.52
Home & Kitchen    3108945.78
Beauty            3057387.79
Name: Purchase_Amount, dtype: float64

Revenue by country

In [39]:
revenue_by_country = df.groupby('Country')['Purchase_Amount'].sum().sort_values(ascending=False)
print(revenue_by_country)

Country
France       2545739.19
Canada       2544335.12
USA          2541220.22
Mexico       2534475.67
Australia    2514911.65
Brazil       2507287.54
India        2503542.71
Germany      2502442.20
Japan        2492312.20
UK           2471723.15
Name: Purchase_Amount, dtype: float64

Customer lifetime value

In [79]:
aov = df['Purchase_Amount'].mean()

purchase_frequency = len(df) / df['User_Name'].nunique()

repeat_rate = (df['User_Name'].value_counts() > 1).sum() / df['User_Name'].nunique()

churn_rate = 1 - repeat_rate
expected_lifespan_periods = 12

clv_lifespan = aov * purchase_frequency * expected_lifespan_periods
print(f"CLV Proxy (12 periods): ${clv_lifespan:,.2f}")

if churn_rate > 0:
    clv_churn = (aov * purchase_frequency) / churn_rate
    print(f"CLV (churn model): ${clv_churn:,.2f}")
else:
    print("CLV (churn model): Not reliable because churn rate is 0.")

CLV Proxy (12 periods): $3,018,958.76
CLV (churn model): Not reliable because churn rate is 0.